### PR TITLE
composer setup bin-dir command doc

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
I'm thinking about some doc update for user that prefer to use `vendor/bin/kahlan` or `bin/kahlan`, any suggestion wording ?

**Comment by jails** [comment]
You mean something like that ?

> The Kahlan package is installed with a vendor library accessible through `vendor/bin/kahlan` by default. However, you can [configure its location like all other composer vendor binaries.](https://getcomposer.org/doc/articles/vendor-binaries.md#can-vendor-binaries-be-installed-somewhere-other-than-vendor-bin-)

**Comment by samsonasik** [comment]
yes, however, the `bin/kahlan` command itself need to be updated

**Comment by jails** [comment]
I'm not sure to get what you mean.

**Comment by samsonasik** [comment]
the doc updated for what i mean, to point `vendor/bin/kahlan` instead of `bin/kahlan`

**Comment by samsonasik** [comment]
merge-able now ?

**Comment by samsonasik** [comment]
I'm merging it for now.

**Pull request merged**
