### PR TITLE
docs($matchers): add example of does not throw

### LINKED ISSUE #21: Add example of `use` with a closure
Given the following snippet:

```php
it('errors if handle is not registered', function () {
  $dependencies = $this->dependencies;
  $dependencies->registered = ['foo' => 'bar'];
  $closure = function () {
    get_dep_for_handle($dependencies, 'baz');
  };
  expect($closure)->toThrow();
});
```

Applied against the following code:

```php
function get_dep_for_handle( $instance, $handle ) {
	return $instance->registered[ $handle ];
}
```

The test passes. But not because of the logical assertion being made. It throws in this case because `$dependencies` is not defined within the scope of the closure. As a result, please consider adding some examples of `use` to the docs to help prevent this kind of false positive from occurring in test implementations.

### PR DESCRIPTION
**Pull request by ghost**
uses `use` to make identifier available inside closure scope

closes #21

### CODE REVIEW

**Comment by jails** [comment]
Not sure `$this->dependencies` & `getRegistered` are required here. Any chance to provide a self contained example instead ?

**Comment by ghost** [comment]
> Any chance to provide a self contained example instead ?

If you can think of something I'd be happy to update the pull. But in this case I felt it was better to provide a more realistic scenario as to something contrived as I assume readers are smart and will see the pattern and run with it. I'm indifferent to changing, however, if you can come up with something more pithy.

**Comment by jails** [comment]
What to you think about the following spec to show `toThrow()` and `use` statement example of use at the same time ?

```php
it("calls the closure under the hood", function() {
    $count = 0;
    $closure = function() use (&$count) {
        $count++;
    };
    expect($closure)->not->toThrow(); //The closure is called here
    expect($count)->toBe(1);
});
```

**Comment by ghost** [comment]
@jails good stuff. covers a bunch of needs and removes the ambiguity I was introducing. pull updated

**Comment by ghost** [comment]
One sec. Need to tweak the title

**Comment by ghost** [comment]
Okay. All set 👏

**Comment by jails** [comment]
:+1:

**Pull request merged**
